// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6o8WbERDzK6bkc6My5cVX2xWuWU5jmoI',
    appId: '1:745414179019:web:cf7fa58b0d222c4d1e434e',
    messagingSenderId: '745414179019',
    projectId: 'todo-fcm-7de07',
    authDomain: 'todo-fcm-7de07.firebaseapp.com',
    storageBucket: 'todo-fcm-7de07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVGuE7-9Ms-hDDuswJMMnfkZmrq3Fuj0',
    appId: '1:745414179019:android:c43c90b0af2681fc1e434e',
    messagingSenderId: '745414179019',
    projectId: 'todo-fcm-7de07',
    storageBucket: 'todo-fcm-7de07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbO2K4qBAzR_3WaclEDQqNIMsVo6e1XY',
    appId: '1:745414179019:ios:315e5b2e24b450d21e434e',
    messagingSenderId: '745414179019',
    projectId: 'todo-fcm-7de07',
    storageBucket: 'todo-fcm-7de07.firebasestorage.app',
    iosBundleId: 'com.example.todoFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbO2K4qBAzR_3WaclEDQqNIMsVo6e1XY',
    appId: '1:745414179019:ios:315e5b2e24b450d21e434e',
    messagingSenderId: '745414179019',
    projectId: 'todo-fcm-7de07',
    storageBucket: 'todo-fcm-7de07.firebasestorage.app',
    iosBundleId: 'com.example.todoFcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6o8WbERDzK6bkc6My5cVX2xWuWU5jmoI',
    appId: '1:745414179019:web:f534845d735922f71e434e',
    messagingSenderId: '745414179019',
    projectId: 'todo-fcm-7de07',
    authDomain: 'todo-fcm-7de07.firebaseapp.com',
    storageBucket: 'todo-fcm-7de07.firebasestorage.app',
  );
}
